// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate.

package authdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
