// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate.

package workspacedb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
