// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate.
// source: workspace.sql

package workspacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace.workspaces (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerID)
	var w Workspace
	err := row.Scan(&w.ID, &w.Name, &w.OwnerID, &w.CreatedAt, &w.UpdatedAt)
	return w, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, owner_id, created_at, updated_at FROM workspace.workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var w Workspace
	err := row.Scan(&w.ID, &w.Name, &w.OwnerID, &w.CreatedAt, &w.UpdatedAt)
	return w, err
}

const listWorkspacesByOwner = `-- name: ListWorkspacesByOwner :many
SELECT id, name, owner_id, created_at, updated_at FROM workspace.workspaces
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var workspaces []Workspace
	for rows.Next() {
		var w Workspace
		if err := rows.Scan(&w.ID, &w.Name, &w.OwnerID, &w.CreatedAt, &w.UpdatedAt); err != nil {
			return nil, err
		}
		workspaces = append(workspaces, w)
	}
	return workspaces, rows.Err()
}
